name: build-and-push
on:
  push:
    branches: ["main"]
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: ap-northeast-2
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - run: aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build & Push (rl-sim CPU runtime)
        run: |
          docker buildx build \
            -f docker/cpu/Dockerfile \
            -t $ECR_REGISTRY/rl-sim:latest \
            --platform linux/arm64,linux/amd64 \
            --push .

      - name: Build & Push (rl-api CPU runtime)
        run: |
          docker buildx build \
            -f docker/cpu/Dockerfile \
            -t $ECR_REGISTRY/rl-api:latest \
            --platform linux/arm64,linux/amd64 \
            --push .
